GET http://localhost:9999/api/person
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:9999/api/person/0
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:9999/api/person
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name":"Clark Kent","age":20}

###

PUT http://localhost:9999/api/person
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":0,"name":"Bruce Wayne","age":40}

###

DELETE http://localhost:9999/api/person/0
Accept: */*
Cache-Control: no-cache

###

